### ISSUE TITLE
[Question] Trying to install RL-Studio

### ISSUE THREAD

**Issue by sergiopaniego** [JdeRobot/RL-Studio#44]
I'm trying to install the repository with all the dependencies. 
I'm finding some issues finding the latest installations instructions.

Following the root [README](https://github.com/JdeRobot/RL-Studio/blob/main/README.md), I get stuck at the [Install rl-studio](https://github.com/JdeRobot/RL-Studio/blob/main/README.md#install-rl-studio) step, with the following error output: 

```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /root/RL-Studio/rl_studio
```

That `setup.py` file is missing in the repo.

With the [webpage installation instructions](https://jderobot.github.io/RL-Studio/install/), I run all the steps until the last one:

```
python main_rlstudio.py -n qlearn -a f1 -e simple -f config.yaml 
```

but this one complains about a missing rl_studio package. I believe that since the first step that I describe is not completed, the second error appears. 

Could you give me further instructions about how to proceed on the installation?

@igarag

**Comment by igarag** [comment]
The `setup.py` file is not necessary because we have the `pyproject.toml` (from Poetry) which centralizes in one place the same functionality. Reviewing the documentation I see that I forgot the instructions to create the virtual environment and install all the dependencies inside. Try isolating the code with the virtual environment. Another option is to use the Poetry environment with: 

```bash
poetry run python main_rlstudio.py -n qlearn -a f1 -e simple -f config.yaml
```

Another test is to install the library locally **within the virtual environment**. This functionality I have to check because I think that with the Poetry environment you already have everything, but I still have to confirm it. You can do it with Pip but, the goal is to use Poetry as a dependency and library manager.

```bash
pip install -e .
```

Thanks for the report, we keep moving forward.

**Comment by sergiopaniego** [comment]
I have moved to the `poetry` based approximantion.
After running:

```
poetry install
# and the command you provided
poetry run python main_rlstudio.py -n qlearn -a f1 -e simple -f config.yaml
``` 
it returns an error about a missing dependency:

``` 
pydantic
``` 

It's solved installing it as follows:

``` 
poetry add 'pydantic[email]'
``` 

then running again the command you provided, Gazebo opens but a timeout closes everything (`"/F1ROS/cameraL/image_raw"` located in `f1_env_camera.py`). Modifying that line to a higher value

```
            image_data = rospy.wait_for_message(
                "/F1ROS/cameraL/image_raw", Image, timeout=100
            )
```

makes the simulator start properly, with the car at some position in the circuit, but it doesn't do anything else.

Following steps? What about that timeout? 

**Side note:**
I'm running all the project on a Docker image, to keep everything isolated. The image is the one developed for Behavior Metrics that already has ROS Noetic-Gazebo 11 installed.

**Comment by sergiopaniego** [comment]
The image topic seems to be running:

```
root@b9ac2e11ce76:~# rostopic list
/F1ROS/cameraL/image_raw
/F1ROS/cmd_vel
/F1ROS/odom
/clock
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/rosout
/rosout_agg
/tf

```

**Comment by rubenlucas93** [comment]
Hi Sergio!

Right now I don´t see what could be the solution. Could you share the logs when reproducing the error?

Thanks!

**Comment by sergiopaniego** [comment]
Hi again @rubenlucas93 @pjfernandecabo!!

I'm again trying to install RL-Studio following the root [README](https://github.com/JdeRobot/RL-Studio).

Some ideas:

* When running the first command in the README regarding apt-get install, an error appears:

```
E: Package 'python-pip' has no installation candidate
E: Unable to locate package python3-pyqt4
E: Unable to locate package pyqt4-dev-tools
E: Package 'qt4-qmake' has no installation candidate
E: Package 'libqt4-dev' has no installation candidate
```
* When trying to install poetry with the current command, the error is the following:

```
Version 1.2.0 is not supported by this installer! Please specify a version prior to 1.2.0a1 to continue!
```

* After installing poetry, it must be added to $PATH.
* After that, when running:
```
poetry run python main_rlstudio.py -n qlearn -a f1 -e simple -f config/config.yaml
```
an error regarding the config file shows up:
```
Traceback (most recent call last):
  File "main_rlstudio.py", line 106, in <module>
    main()
  File "main_rlstudio.py", line 101, in main
    trainer = TrainerFactory(params)
  File "/root/RL-Studio/rl_studio/agents/__init__.py", line 18, in __new__
    return F1Trainer(config)
  File "/root/RL-Studio/rl_studio/agents/f1/train_qlearn.py", line 27, in __init__
    self.env = gym.make(self.env_name, **env_params)
  File "/root/.cache/pypoetry/virtualenvs/rl-studio-cn5bEEh1-py3.8/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/rl-studio-cn5bEEh1-py3.8/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/rl-studio-cn5bEEh1-py3.8/lib/python3.8/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/root/RL-Studio/rl_studio/envs/gazebo/f1/models/__init__.py", line 37, in __new__
    return DQNF1FollowLineEnvGazebo(**config)
  File "/root/RL-Studio/rl_studio/envs/gazebo/f1/models/f1_env_dqn_camera.py", line 584, in __init__
    self.image_resizing = config["image_resizing"] / 100
KeyError: 'image_resizing'
```

I have mocked up those config variables setting them directly in the .py file. 
After that, Gazebo shows up but the timeout is still happening, so nothing happens.

```
process[gazebo-1]: started with pid [7219]
process[gazebo_gui-2]: started with pid [7224]
b9ac2e11ce76# [ INFO] [1662632159.629025740]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1662632159.630251581]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[gazebo-1] process has died [pid 7219, exit code 255, cmd /opt/ros/noetic/lib/gazebo_ros/gzserver -e ode simple_circuit.world __name:=gazebo __log:=/root/.ros/log/a16b7d5e-2f58-11ed-b8b0-0242ac110002/gazebo-1.log].
log file: /root/.ros/log/a16b7d5e-2f58-11ed-b8b0-0242ac110002/gazebo-1*.log
[ WARN] [1662632159.722554276]: Shutdown request received.
[ WARN] [1662632159.722623402]: Reason given for shutdown: [[/gazebo_gui] Reason: new node registered with same name]
[gazebo_gui-2] process has finished cleanly
log file: /root/.ros/log/a16b7d5e-2f58-11ed-b8b0-0242ac110002/gazebo_gui-2*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
```

**Comment by rubenlucas93** [comment]
First of all. The first errors you mentioned are known issues. At least in my case I got those errors also.
I didn't remove nothing just in case I was an isolated case, but since it is reiterative, I think we could update the manual and the poetry files to avoid those errors (at least comments the failed packages) and include also in the manual the command you used to install poetry and what you mentioned regarding the PATH.

Talking about the problem. When you run 
`poetry run python main_rlstudio.py -n qlearn -a f1 -e simple -f config/config.yaml
`
something weird happens. For whatever reason, despite you are passing as an argument "qlearn", the execution flow is going through a different path. As you can see the error is happening in f1_env_**dqn**_camera.py file. 
Try to debug your execution to check why it is launching this unexpected environment. I will take a look to the config.yaml we have in the repo. It may be prepared to launch dqn so yo may need to modify it to launch qlearn.

Regarding the "timeout is still happening". Do you mean that gazebo closes by itself? Or it is blocked in "waitForService" forever?

**Comment by rubenlucas93** [comment]
Yo got it! Now we have an issue opened to stabilize the f1 dqn launching. Could you go to the issue 74 branch and try to execute it from there and see if the problem is just mine?

Thanks!
